version: "3"
services:
  swagger:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./public:/usr/share/nginx/html
#    environment:
#      - BASE_API_URL=localhost:8082
    ports:
      - "8082:80"
      - "8083:81"